name: Build and publish to NPM on new releases
on:
  push:
    branches:
      - main
jobs:
  npm-publish-revchiver:
    name: Build (and, if relevant, publish) Revchiver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare env
        run: |
          cd packages/revchiver
          yarn install --prod=false
          yarn build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: Revchiver v(\\S+)"
          workspace: "./packages/revchiver"
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  npm-publish-termivolt:
    name: Build (and, if relevant, publish) Termivolt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare env
        run: |
          cd packages/termivolt
          yarn install --prod=false
          yarn build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^release: Termivolt v(\\S+)"
          workspace: "./packages/termivolt"
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
